on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t devops-app .

    - name: Tag image
      run: docker tag devops-app 052714/devops-app:${{ github.sha }}

    - name: Push image
      run: docker push 052714/devops-app:${{ github.sha }}

    - name: Update deployment.yaml image
      run: |
        sed -i "s|image: .*|image: 052714/devops-app:${{ github.sha }}|g" deployment.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push
